var fs = require('fs');
var package = require('../package.json');

/**
 * Create version.ts and sync the repos i.e. master and develop branches
 * @param {*} pluginConfig The semantic-release plugin config
 * @param {*} context The context provided by semantic-release
 */
async function prepare(_pluginConfig, _context) {
	var data = `// THIS IS AN AUTO GENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
export const VERSION = '${package.version}';
`;

	// write data to file sample.html
	fs.writeFile(
		'src/version.ts',
		data,
		// callback function that is called after writing file is done
		function(err) {
			if (err) throw err;
			// if no error
			console.log('Version file created successfully.');
		}
	);
}

module.exports = { prepare };
