# Used on master and staging branches
name: Production CI

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - 'master' # Push events on master branch
      - 'next' # Push events on staging branch
      - 'alpha' # Push events on alpha branch
      - 'beta' # Push events on beta branch

jobs:
  test:
    name: Test, Build & Release
    runs-on: ubuntu-latest
    container:
      image: bluebasejs/github-actions-image
      options: --privileged

    strategy:
      matrix:
        node-version: [12]

    steps:
      - uses: actions/checkout@v1

      - name: Install Dependencies
        run: yarn install

      - name: Unit Tests
        run: yarn test:only --coverage --logHeapUsage --ci

      - name: Test Lint
        run: yarn test:lint

      - name: Test Prettier
        run: yarn test:prettier

      - name: Build
        run: yarn build

      - name: Set Unsafe-Perm
        run: npm set unsafe-perm true

      - name: Semantic Release
        run: npx semantic-release@beta
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

 